version: '2'

services:
  db:
    image: postgres
  web:
    build: .
    command: python accounts.cca.edu/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  migration:
    build: .
    command: python accounts.cca.edu/manage.py migrate --noinput
    volumes:
      - .:/code
